#!/bin/bash
#
# $Id$
#
# Icetray environment script.
#
# modified to work with pone-offline

if [ "$1" = "help" ]
    then
    echo "Usage: $0 [SHELL]"
    echo "Spawn a new shell with an Icetray environment loaded"
    echo ""
    echo "SHELL can specified with or without a full path.  If SHELL"
    echo "is omitted the login shell is used by default."
    echo "Examples:"
    echo "   ./env-shell.sh"
    echo "   ./env-shell.sh tcsh"
    echo "   ./env-shell.sh /bin/tcsh"
    echo ""
    echo "To exit the Icetray environment simply exit the new shell."
    echo ""
    exit 1
fi

if [ -z "$1" ]
    then # user did not specify a shell
    NEW_SHELL=$SHELL 
    # only exit if no shell specified on command line *and* env already loaded 
    if [ -n "$I3_SHELL" ] 
    then  
    echo "****************************************************************"
    echo "You are currently in a shell with an Icetray environment loaded."
    echo "Please exit the current shell and re-run $0 from a clean shell."
    echo "****************************************************************"
    echo "Environment not (re)loaded."
    exit 2
    fi
else
    NEW_SHELL=$1
    shift
    ARGV="$@"
fi

_I3_SHELL=$NEW_SHELL

pushd `dirname $0` >/dev/null
BASEDIR='/usr/local/icetray'
popd >/dev/null

# Check for expected files to determine SRC and BUILD locations
if [ -f "$BASEDIR/requirements.txt" ]; then
    _I3_SRC=$BASEDIR
elif [ -f "$BASEDIR/src/requirements.txt" ]; then
    _I3_SRC=$BASEDIR/src
else
    echo "****************************************************************"
    echo "ERROR: _I3_SRC NOT FOUND"
    echo "Unable to determine appropriate _I3_SRC location"
    echo "Expected to find requirements.txt in $BASEDIR or $BASEDIR/src"
    echo "****************************************************************"
    exit 1
fi

if [ -f "$BASEDIR/env-shell.sh" ]; then
    _I3_BUILD=$BASEDIR
elif [ -f "$BASEDIR/build/env-shell.sh" ]; then
    _I3_BUILD=$BASEDIR/build
else
    echo "****************************************************************"
    echo "ERROR: _I3_BUILD NOT FOUND"
    echo "Unable to determine appropriate _I3_BUILD location"
    echo "Expected to find env-shell.sh in $BASEDIR or $BASEDIR/build"
    echo "****************************************************************"
    exit 1
fi

_PONE_SRC="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

# Check for I3_BUILD mismatch
if [ -n "$I3_BUILD" -a "$I3_BUILD" != "$_I3_BUILD" ]
then
    echo "****************************************************************"
    echo "I3_BUILD CHANGED"
    echo "It appears that you are attempting to load an icetray environment different"
    echo "than the one already loaded"
    echo "          This I3_BUILD=$_I3_BUILD"
    echo "Already loaded I3_BUILD=$I3_BUILD"
    echo "****************************************************************"
    echo "Environment not (re)loaded."
    exit 2
fi

_ROOTSYS=''
_LD_LIBRARY_PATH=$_I3_BUILD/lib:$_I3_BUILD/lib/tools:/usr/local/OpenBLAS::$LD_LIBRARY_PATH
_DYLD_LIBRARY_PATH=$_I3_BUILD/lib:$_I3_BUILD/lib/tools:$DYLD_LIBRARY_PATH

_PYTHONPATH=$_I3_BUILD/lib:$PYTHONPATH
_PATH=$_I3_BUILD/bin:$PATH


_HIPPO_FOUND=
if [ "${_HIPPO_FOUND}" = 1 ]; then
    _LD_LIBRARY_PATH=:::${_LD_LIBRARY_PATH}
    _DYLD_LIBRARY_PATH=:${_DYLD_LIBRARY_PATH}
    _PYTHONPATH=:${_PYTHONPATH}
fi

_HDF5_USE_FILE_LOCKING=${HDF5_USE_FILE_LOCKING:-FALSE}

TOPBAR="************************************************************************"
WIDTH=`echo "$TOPBAR" | wc -c`

WIDTH=$(( $WIDTH-2 ))

printctr()
{
    LEN=`echo "$*" | wc -c`
    LOFFSET=$(( ($WIDTH-$LEN)/2 ))
    ROFFSET=$(( $WIDTH-$LOFFSET-$LEN ))

    FORMAT="*%${LOFFSET}s%s%${ROFFSET}s*\n"
    printf $FORMAT " " "$*" " "
}

I3VERSION=$(grep -i 'project(icetray' "$_I3_SRC/cmake/toplevel.cmake" | grep -oP 'VERSION\s+\K[0-9]+\.[0-9]+\.[0-9]+')
PTAG=$(<.versiontag)
RED='\033[1;31m'
NC='\033[0m'

if [ -z "$ARGV" ]
    then
    printf "$TOPBAR\n"
    printctr ""
    printctr "W E L C O M E  to  I C E T R A Y"
    printctr " Version $I3VERSION "
    printctr " "
    printctr " P-ONE Offline Extensions Loaded"
    if [[ "$I3VERSION" != "$PTAG" ]]; then
        printctr "    $(echo -e "${RED} WARNING!!, PONE_OFFLINE EXPECTS ICETRAY VERSION $PTAG ${NC}")     "
    fi
    printctr ""
    printctr ""
    printf "$TOPBAR\n"
    printf "\n"
    printf "Icetray environment has:\n"
    printf "   I3_SRC       = %s\n" $_I3_SRC
    printf "   I3_BUILD     = %s\n" $_I3_BUILD
    echo   "   "$(python3 -V 2>&1)
fi

if [ -z "$I3_SHELL" ] # a clean, first invocation
    then

    # GEANT4_ENV_VARS pulls in GEANT4 variables,
    # generated by cmake/make_geant4_env.py

    PATH=$_PATH \
    LD_LIBRARY_PATH=$_LD_LIBRARY_PATH \
    DYLD_LIBRARY_PATH=$_DYLD_LIBRARY_PATH \
    PYTHONPATH=$_PYTHONPATH \
    ICETRAY_CLASSPATH=$_ICETRAY_CLASSPATH \
    I3_PLATFORM="" \
    I3_SRC=$_I3_SRC \
    I3_BUILD=$_I3_BUILD \
    ROOTSYS=$_ROOTSYS \
    I3_SHELL=$_I3_SHELL \
    PONESRCDIR=$_PONE_SRC \
    HDF5_USE_FILE_LOCKING=$_HDF5_USE_FILE_LOCKING \
     \
    $NEW_SHELL --rcfile <(echo 'export PS1="\e[0;32m[I3T]:\W\$ \e[m ";  export PYTHONPATH=$PYTHONPATH:$(pwd)') "$@"

else  # not clean, use previous environment
    $NEW_SHELL "$@"
fi

STATUS=$?

if [ -z "$ARGV" ]
then
    echo "Exited Icetray Environment."
fi
exit $STATUS

